package at.fhhagenberg.sqelevator.controller;

import at.fhhagenberg.sqelevator.model.ApplicationModel;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class EccController extends WindowAdapter {

    private ApplicationModel model;

    public EccController(ApplicationModel model) {
        this.model = model;
    }

    public void initApplication() {
        model.initApplication();
    }

    // Autogenerated shit

    @Override
    public void windowOpened(WindowEvent e) {

    }

    @Override
    public void windowClosing(WindowEvent e) {
        super.windowClosing(e);
        e.getWindow().dispose();
    }

    @Override
    public void windowClosed(WindowEvent e) {

    }

    @Override
    public void windowIconified(WindowEvent e) {

    }

    @Override
    public void windowDeiconified(WindowEvent e) {

    }

    @Override
    public void windowActivated(WindowEvent e) {

    }

    @Override
    public void windowDeactivated(WindowEvent e) {

    }
}
