name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    - name: Run SonarCloud
        uses: sonarcloud/analyse
        with:
          projectKey: project-sqelevator-mcm-team-5-1
          orgnization: fhhagenberg-sqe
          hostUrl: https://sonarcloud.io
    - name: Build with Maven
#       run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      run: mvn -B package --file pom.xml